<?php

/**
 * Implements hook_libraries_info_alter().
 *
 * To get into this hook, add a new key to the library definition in
 * hook_libraries_info().
 *
 * Here's an example:
 *
 * 'cdn' => array(
 *   'aliases' => array('ol3', 'openlayers3'),
 *   'options' => array(
 *     'weight' => 0,
 *     'group' => $js_css_group,
 *   ),
 * )
 *
 * - aliases: array, if the library has different names.
 * - options: array, this array will be applied to each file definition,
 *            see drupal_add_TYPE() (js or css) to see which are the keys.
 *
 * @param $info
 */
function libraries_cdn_libraries_info_alter(&$info) {
  foreach ($info as $library_name => &$library) {
    $variants = array();
    if (isset($library['cdn'])) {
      if (isset($library['cdn']['processed'])) {
        continue;
      }
      $options = $library['cdn'];
      if (!isset($options['options'])) {
        $options['options'] = array();
      }
      if (!isset($options['plugins']) || empty($options['plugins'])) {
        $options['plugins'] = \Drupal\libraries_cdn\LibrariesCDN::getAvailableCDN();
      }

      if (!isset($options['aliases'])) {
        $options['aliases'] = array();
      }
      $options['aliases'] += array($library_name);
      $options['aliases'] = array_unique($options['aliases']);

      foreach ($options['aliases'] as $alias) {
        foreach ($options['plugins'] as $plugin) {
          \Drupal\libraries_cdn\LibrariesCDN::setPlugin($plugin, $alias);
          $variants += \Drupal\libraries_cdn\LibrariesCDN::getLibrariesVariants($options['options']);
        }
      }

      if (!isset($library['variants'])) {
        $library['variants'] = array();
      }
      $library['variants'] += $variants;
    }
  }
  $library['cdn']['processed'] = TRUE;
}
